name: GitHub integration testops

on:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://dev.github.com
      TEST_BROWSER:
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1.0.0
        with:
          allure-endpoint: https://demo.testops.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 338
          allurectl-version: 2.15.1
      - name: Build with Gradle
        run: |
          allurectl watch -- ./gradlew clean test
          export $( allurectl job-run env)
          printenv | grep ALLURE_
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
          TEST_BROWSER: ${{ github.event.inputs.TEST_BROWSER }}
      - name: Get ALLURE_ environments
        run: | 
          printenv | grep TEST_
          printenv | grep ALLURE_
          printenv | grep TEST_
      - name: Get GITHUB_ environments
        run: | 
          printenv | grep GITHUB_
      - name: List results
        run: ls -la ${ALLURE_RESULTS}
      - name: List allurectl dir
        run: |
          ls -lah ~/ || true
          ls -lah ~/.allure || true
          cat ~/.allure/testplan.json || true
          allurectl ci env
          
